---
- hosts: all
  become: yes
  tasks:
  - name: install docker
    apt: 
      pkg: docker.io
      state: present

  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true
 
  - name: pull the image
    command: docker pull arunkumarkn/addressbook:latest

  - name: deploy addressbook application
    command: docker run -itd -p 8080:8080 arunkumarkn/addressbook:latest

